name: Deploy To Production

on:
  push:
    tags:
      - "*"
  pull_request:
    branches:
      - "master"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Release package
        uses: BigWigsMods/packager@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}